### PR TITLE
Add search result highlight to search result highlight display

### LINKED ISSUE #83: Search results: set consistent view mode [localgov_events]
As part of reviewing the search functionality, it has become apparent that there is no consistent presentation of search results across the distribution.

We need to

- [ ]  ensure each content type has a search_result display node
- [ ]  configure the search_result display mode to have the appropriate fields

In the case of localgov_events, we need to ensure appropriate configuration for

- [ ]  localgov_event

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #83

Usual cavet about using search_api as dependency applies.
(If not using search_api, the search result display will be blank)

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Works for me! Thanks @andybroomfield !

**Review by ekes — COMMENTED** [review]
Tested manually and it works.

If https://github.com/localgovdrupal/localgov_news/pull/74 makes sense I'd be super happy if we add similar simple tests for the LocalGov Search integration.

**Comment by finnlewis** [comment]
@ekes would like us to add a test for this, following the example on https://github.com/localgovdrupal/localgov_step_by_step/pull/64/files#diff-afe33a5fb745c57e43f66de12ec75bfae6c2526c9e584f3e522a73eeb73800e6

**Comment by finnlewis** [comment]
@ekes how does this look now? 

https://github.com/localgovdrupal/localgov_events/pull/86/files#diff-8290e4e8b9256e58d89fae391f18efb498810be0c1eaa1802408df371f9ef616

**Comment by finnlewis** [comment]
@ekes looking OK to merge?

**Comment by ekes** [comment]
Just the use statement in the test that's making the coding standards fail.

**Pull request merged**
