### PR TITLE
3.0.1 release

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
@ekes any idea why we're getting this error in the tests?

```
1) Drupal\Tests\localgov_events\Functional\LocalgovIntegrationTest::testLocalgovSearch
Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'localgov_event_date_timezone' cannot be null: INSERT INTO "test78393096node__localgov_event_date" ("entity_id", "revision_id", "bundle", "delta", "langcode", "localgov_event_date_value", "localgov_event_date_end_value", "localgov_event_date_rrule", "localgov_event_date_timezone", "localgov_event_date_infinite") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array
(
    [:db_insert_placeholder_0] => 1
    [:db_insert_placeholder_1] => 1
    [:db_insert_placeholder_2] => localgov_event
    [:db_insert_placeholder_3] => 0
    [:db_insert_placeholder_4] => en
    [:db_insert_placeholder_5] => [20](https://github.com/localgovdrupal/localgov_events/actions/runs/7711162659/job/21016601654?pr=134#step:5:21)[24](https://github.com/localgovdrupal/localgov_events/actions/runs/7711162659/job/21016601654?pr=134#step:5:25)-01-30T12:49:31
    [:db_insert_placeholder_6] => 2024-01-30T12:49:31
    [:db_insert_placeholder_7] => 
    [:db_insert_placeholder_8] => 
    [:db_insert_placeholder_9] => 0
)

**Comment by finnlewis** [comment]
@ekes any ideas?

**Comment by ekes** [comment]
Test event didn't even have a date. Added one.

**Comment by ekes** [comment]
> Test event didn't even have a date. Added one.

Sorry forgot to make a PR for it in amongst all the other issues. https://github.com/localgovdrupal/localgov_events/pull/137

**Pull request merged**
