### PR TITLE
Remove Date_recur patch as now included in date_recur 3.1

### LINKED ISSUE #69: Patch no longer needed
Hey there,

Patch is no longer needed for the data_recur module

Could this be looked at asap?, I can verify that the code in the patch is now within the module itself.
Sadly blocking a deployment we need to push up

```
  Cannot apply patch Fix schema #3173876 (https://www.drupal.org/files/issues/2020-10-02/views-field-date-recur-date-schema-3173876-5.patch)!
```

I tried creating a PR to make life easier but I think I need some permission or something. (First time creating a pr to an outside repo - forgive me if there's genuinely a way to do this and i missed it!)

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #69

Patch should now be part of drupal/date_recur 3.1+

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Looks good to me, thanks @andybroomfield

**Review by stephen-cox — APPROVED** [review]
Not tested but the patch is definitely in the module so all good. Thanks @andybroomfield

**Comment by finnlewis** [comment]
@andybroomfield we're just discussing this in the Tech drop-in call with @ekes and @stephen-cox . 

Considering this is blocking https://github.com/benlamptey, we're going to go ahead and merge it and make a release.

**Comment by benlamptey** [comment]
amazing, thank you all!!

**Pull request merged**
