### PR TITLE
Default events filter start date to today if blank

### PR DESCRIPTION
**Pull request by andybroomfield**
Initial set the start date as today if not set

### CODE REVIEW

**Comment by finnlewis** [comment]
@andybroomfield tested this locally and it does seem to do the job.

**Comment by andybroomfield** [comment]
Thanks @finnlewis.
I think we needs some tests for this behaviour.

**Comment by andybroomfield** [comment]
I'll make this ready for review, lets add a new issue for the tests as we need to get events tests anyway.

**Comment by finnlewis** [comment]
Just discussing this at 'merge monday' and @ekes, @andybroomfield and I are in favour of merging this in now to release the fix, then adding another issue to add some tests.

**Review by finnlewis — APPROVED** [review]

**Comment by finnlewis** [comment]
Merge away @andybroomfield !

**Pull request merged**
